apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: discord-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: flux
        property: discord_webhook
