# cert-manager controller exposes Prometheus metrics on port 9402 by default.
# The metrics Service is created by the Helm chart automatically — we just
# need to scrape it.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: cert-manager
  endpoints:
    - port: tcp-prometheus-servicemonitor
      interval: 60s
      path: /metrics
