apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: prometheus
  labels:
    app.kubernetes.io/name: minio
spec:
  namespaceSelector:
    matchNames:
      - minio
  selector:
    matchLabels:
      app: minio
  endpoints:
    - port: api
      interval: 60s
      scheme: http
      path: /minio/v2/metrics/cluster
      bearerTokenSecret:
        name: minio-prometheus-token
        key: token
