apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blackbox-exporter/configmap.yaml
  - blackbox-exporter/deployment.yaml
  - blackbox-exporter/service.yaml
  - kube-state-metrics/rbac.yaml
  - kube-state-metrics/flux-config.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  - postgres-exporter/secrets.yaml
  - postgres-exporter/deployment.yaml
  - postgres-exporter/service.yaml
