apiVersion: v1
kind: Secret
metadata:
  name: directus-credentials
  namespace: directus
type: Opaque
stringData:
  SECRET: "CHANGE_ME"
  ADMIN_EMAIL: "admin@example.com"
  ADMIN_PASSWORD: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  STORAGE_S3_KEY: "minio"
  STORAGE_S3_SECRET: "CHANGE_ME"
