apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victorialogs-statefulset.yaml
  - victorialogs-service.yaml
  - fluent-bit-rbac.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-daemonset.yaml
