apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victorialogs
  namespace: vm
  labels:
    app.kubernetes.io/name: victorialogs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victorialogs
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
