apiVersion: v1
kind: Service
metadata:
  name: victorialogs
  namespace: vm
  labels:
    app.kubernetes.io/name: victorialogs
spec:
  selector:
    app.kubernetes.io/name: victorialogs
  ports:
    - name: http
      port: 9428
      targetPort: 9428
