apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/ingress/cert-manager-issuer
  prune: true
  force: true
  dependsOn:
    - name: infra-cert-manager
