apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Ingress & TLS
  - infra-traefik.yaml
  - infra-cert-manager.yaml
  - infra-cert-manager-issuer.yaml

  # Secret management
  - infra-external-secrets-operator.yaml
  - infra-secret-store.yaml
  - infra-secret-reloader.yaml

  # GitOps automation
  - infra-image-automation.yaml
  - infra-receiver.yaml

  # Applications
  - apps-postgres.yaml
  - apps-minio.yaml
  - apps-directus.yaml
  - apps-website.yaml
  - apps-minio-init.yaml

  # Observability
  - obs-victoriametrics-operator.yaml
  - obs-exporters.yaml
  - obs-victoriametrics.yaml
  - obs-alertmanager.yaml
  - obs-victorialogs.yaml
  - obs-grafana.yaml
