apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: obs-grafana
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/observability/grafana
  prune: true
  wait: true
  dependsOn:
    - name: obs-victoriametrics
    - name: obs-victorialogs
    - name: infra-cert-manager-issuer
