apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-basic-auth
  namespace: vm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: alertmanager
        property: basic_auth_users
