apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres
        property: user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres
        property: database
