apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: external-endpoints
  namespace: vm
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  interval: 60s
  scrapeTimeout: 10s
  module: http_2xx
  vmProberSpec:
    url: blackbox-exporter.vm.svc.cluster.local:9115
  targets:
    staticConfig:
      targets:
        - https://website.vdemirev.com
        - https://directus.vdemirev.com
      labels:
        probe: external
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: external-endpoints-auth
  namespace: vm
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  interval: 60s
  scrapeTimeout: 10s
  module: http_2xx_no_tls_check
  vmProberSpec:
    url: blackbox-exporter.vm.svc.cluster.local:9115
  targets:
    staticConfig:
      targets:
        - https://minio.vdemirev.com
      labels:
        probe: external
