apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-scrape.yaml
  - kube-state-metrics-scrape.yaml
  - minio-scrape.yaml
  - node-exporter-scrape.yaml
  - postgres-exporter-scrape.yaml
  - traefik-scrape.yaml
  - flux-scrape.yaml
  - external-probes.yaml
