apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: postgres-exporter
  namespace: vm
  labels:
    app.kubernetes.io/name: postgres-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres-exporter
  endpoints:
    - port: metrics
      interval: 30s
