apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-credentials
  namespace: directus
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: directus-credentials
    creationPolicy: Owner
  data:
    - secretKey: KEY
      remoteRef:
        key: directus
        property: key
    - secretKey: SECRET
      remoteRef:
        key: directus
        property: secret
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: directus
        property: admin_email
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: directus
        property: admin_password
    - secretKey: DB_PASSWORD
      remoteRef:
        key: postgres
        property: password
    - secretKey: STORAGE_S3_KEY
      remoteRef:
        key: minio
        property: access_key
    - secretKey: STORAGE_S3_SECRET
      remoteRef:
        key: minio
        property: secret_key
    - secretKey: SYNC_WEBHOOK_SECRET
      remoteRef:
        key: email
        property: SYNC_WEBHOOK_SECRET
