apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: victoria-metrics
  namespace: vm
spec:
  replicaCount: 1
  evaluationInterval: "30s"
  datasource:
    url: http://vmsingle-victoria-metrics.vm.svc:8429
  notifiers:
    - url: http://vmalertmanager-main.vm.svc:9093
  ruleSelector: {}
  ruleNamespaceSelector: {}
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi
