apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-exporter-credentials
  namespace: vm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-exporter-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATA_SOURCE_NAME: "postgresql://{{ .user }}:{{ .password }}@postgres.postgres.svc.cluster.local:5432/{{ .database }}?sslmode=disable"
  data:
    - secretKey: user
      remoteRef:
        key: postgres
        property: user
    - secretKey: password
      remoteRef:
        key: postgres
        property: password
    - secretKey: database
      remoteRef:
        key: postgres
        property: database
