apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: victoria-metrics
  namespace: vm
spec:
  replicaCount: 1
  retention: 120h
  configSecret: alertmanager-config
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
