apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: victoria-metrics
  namespace: vm
spec:
  replicaCount: 1
  image:
    repository: quay.io/prometheus/alertmanager
    tag: v0.28.0
  configSecret: alertmanager-config
  secrets:
    - alertmanager-webhook
  retention: 120h
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
