apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vm

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml

configMapGenerator:
  - name: discord-relay-script
    files:
      - relay.py

generatorOptions:
  disableNameSuffixHash: true
