apiVersion: v1
kind: Service
metadata:
  name: discord-relay
  namespace: vm
  labels:
    app.kubernetes.io/name: discord-relay
spec:
  selector:
    app.kubernetes.io/name: discord-relay
  ports:
    - name: http
      port: 8080
      targetPort: http
