#!/usr/bin/env bash
# Fetches community Grafana dashboards, normalizes datasource types AND
# rewrites field names to match our Fluent Bit schema, then regenerates
# kustomization.yaml.
#
# Field name normalization:
#   kubernetes_namespace     -> kubernetes.namespace_name
#   kubernetes_pod_name      -> kubernetes.pod_name
#   kubernetes_container_name-> kubernetes.container_name
# These are the field names our Fluent Bit produces (dot-nested, from the
# kubernetes filter with nested Merge_Log). Community dashboards default to
# the flat underscore schema from the VL Helm chart's Vector config.
set -euo pipefail

cd "$(dirname "$0")"

# Format: "id:revision:slug"
DASHBOARDS=(
  "15759:37:k8s-cluster"
  "16714:1:flux"
  "9628:8:postgres"
  "7587:3:blackbox"
  "21550:1:victorialogs-simple"
)

# Hardcode our actual datasource UIDs (from datasources.yaml):
#   prometheus uid = "prometheus"  (VictoriaMetrics, type prometheus)
#   logs uid      = "victorialogs" (VictoriaLogs, type victoriametrics-logs-datasource)
#
# We hardcode rather than use template variables because community dashboards use
# inconsistent variable names (DS_PROMETHEUS, datasource, DS_SIGNCL-PROMETHEUS, etc.)
# and Grafana only resolves template vars by name — mismatches silently break panels.
PROMETHEUS_UID="prometheus"
LOGS_UID="victorialogs"

NORMALIZE="
  # 1. Normalize datasource object refs in panels/targets
  walk(
    if type == \"object\" and has(\"datasource\") then
      if (.datasource | type) == \"object\" then
        if .datasource.type == \"prometheus\" then
          .datasource = {\"type\": \"prometheus\", \"uid\": \"${PROMETHEUS_UID}\"}
        elif (.datasource.type == \"loki\" or .datasource.type == \"victoriametrics-logs-datasource\") then
          .datasource = {\"type\": \"victoriametrics-logs-datasource\", \"uid\": \"${LOGS_UID}\"}
        else . end
      elif (.datasource | type) == \"string\" and (.datasource | length) > 0 then
        # String UID (hardcoded from another installation) — assume prometheus
        .datasource = {\"type\": \"prometheus\", \"uid\": \"${PROMETHEUS_UID}\"}
      else . end
    else . end
  ) |

  # 2. Fix datasource-type template variables so Grafana resolves them correctly
  if .templating.list then
    .templating.list |= map(
      if .type == \"datasource\" and .query == \"prometheus\" then
        .query = \"prometheus\" |
        .current = {\"selected\": false, \"text\": \"VictoriaMetrics\", \"value\": \"${PROMETHEUS_UID}\"} |
        .options = [{\"selected\": true, \"text\": \"VictoriaMetrics\", \"value\": \"${PROMETHEUS_UID}\"}]
      elif .type == \"datasource\" and (.query == \"loki\" or .query == \"victoriametrics-logs-datasource\") then
        .query = \"victoriametrics-logs-datasource\" |
        .current = {\"selected\": false, \"text\": \"VictoriaLogs\", \"value\": \"${LOGS_UID}\"} |
        .options = [{\"selected\": true, \"text\": \"VictoriaLogs\", \"value\": \"${LOGS_UID}\"}]
      elif .type == \"constant\" and (.name | test(\"LOG|LOGS|LOKI\"; \"i\")) then
        .query = \"${LOGS_UID}\" | .current = {\"value\": \"${LOGS_UID}\", \"text\": \"${LOGS_UID}\"}
      elif .type == \"constant\" and (.name | test(\"METRIC|PROM\"; \"i\")) then
        .query = \"${PROMETHEUS_UID}\" | .current = {\"value\": \"${PROMETHEUS_UID}\", \"text\": \"${PROMETHEUS_UID}\"}
      else . end
    )
  else . end
"

# sed script: rewrite LogsQL field names in queries/variables.
# Runs on the already-normalized JSON before we wrap it in ConfigMap.
FIELD_REWRITE='
  s/kubernetes_namespace/kubernetes.namespace_name/g;
  s/kubernetes_pod_name/kubernetes.pod_name/g;
  s/kubernetes_container_name/kubernetes.container_name/g;
'

rm -f configmap-*.yaml

generated=()
for entry in "${DASHBOARDS[@]}"; do
  IFS=':' read -r id revision slug <<< "$entry"
  out="configmap-${slug}.yaml"
  echo ">>> ${id} rev ${revision} -> ${out}"

  json=$(
    curl -sfL "https://grafana.com/api/dashboards/${id}/revisions/${revision}/download" \
      | jq "$NORMALIZE" \
      | sed -E "$FIELD_REWRITE"
  )

  cat > "$out" <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-${slug}
  namespace: grafana
  labels:
    grafana_dashboard: "1"
data:
  ${slug}.json: |
$(echo "$json" | sed 's/^/    /')
EOF
  generated+=("$out")
done

# Regenerate kustomization.yaml to match reality.
{
  echo "# Auto-generated by fetch-dashboards.sh — do not edit by hand."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo ""
  echo "resources:"
  for f in "${generated[@]}"; do
    echo "  - ${f}"
  done
} > kustomization.yaml

echo ""
echo ">>> Done: $(ls configmap-*.yaml | wc -l) configmaps + kustomization.yaml"
