#!/usr/bin/env bash
# Fetches community Grafana dashboards, normalizes datasource types AND
# rewrites field names to match our Fluent Bit schema, then regenerates
# kustomization.yaml.
#
# Field name normalization:
#   kubernetes_namespace     -> kubernetes.namespace_name
#   kubernetes_pod_name      -> kubernetes.pod_name
#   kubernetes_container_name-> kubernetes.container_name
# These are the field names our Fluent Bit produces (dot-nested, from the
# kubernetes filter with nested Merge_Log). Community dashboards default to
# the flat underscore schema from the VL Helm chart's Vector config.
set -euo pipefail

cd "$(dirname "$0")"

# Format: "id:revision:slug"
DASHBOARDS=(
  "15759:37:k8s-cluster"
  "16714:1:flux"
  "9628:8:postgres"
  "7587:3:blackbox"
  "21550:1:victorialogs-simple"
)

NORMALIZE='
  walk(
    if type == "object" and has("datasource") then
      if .datasource | type == "object" then
        if .datasource.type == "prometheus" then
          .datasource = {"type": "prometheus", "uid": "${datasource}"}
        elif .datasource.type == "loki" then
          .datasource = {"type": "victoriametrics-logs-datasource", "uid": "${logs_datasource}"}
        else . end
      else . end
    else . end
  )
'

# sed script: rewrite LogsQL field names in queries/variables.
# Runs on the already-normalized JSON before we wrap it in ConfigMap.
FIELD_REWRITE='
  s/kubernetes_namespace/kubernetes.namespace_name/g;
  s/kubernetes_pod_name/kubernetes.pod_name/g;
  s/kubernetes_container_name/kubernetes.container_name/g;
'

rm -f configmap-*.yaml

generated=()
for entry in "${DASHBOARDS[@]}"; do
  IFS=':' read -r id revision slug <<< "$entry"
  out="configmap-${slug}.yaml"
  echo ">>> ${id} rev ${revision} -> ${out}"

  json=$(
    curl -sfL "https://grafana.com/api/dashboards/${id}/revisions/${revision}/download" \
      | jq "$NORMALIZE" \
      | sed -E "$FIELD_REWRITE"
  )

  cat > "$out" <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-${slug}
  namespace: grafana
  labels:
    grafana_dashboard: "1"
data:
  ${slug}.json: |
$(echo "$json" | sed 's/^/    /')
EOF
  generated+=("$out")
done

# Regenerate kustomization.yaml to match reality.
{
  echo "# Auto-generated by fetch-dashboards.sh — do not edit by hand."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo ""
  echo "resources:"
  for f in "${generated[@]}"; do
    echo "  - ${f}"
  done
} > kustomization.yaml

echo ""
echo ">>> Done: $(ls configmap-*.yaml | wc -l) configmaps + kustomization.yaml"
