apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: website
          image: ghcr.io/tues-2026-pbl-11-klas/websaitut/website:20260412183809-4b1d8dd # {"$imagepolicy": "flux-system:website"}
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://directus.directus.svc.cluster.local:8055
