apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-token
  namespace: website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: directus-token
    creationPolicy: Owner
  data:
    - secretKey: DIRECTUS_TOKEN
      remoteRef:
        key: directus
        property: secret
