apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: email
  namespace: website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: email
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: email
