apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: google-calendar
  namespace: website
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: google-calendar
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_CALENDAR_ID
      remoteRef:
        key: google_calendar
        property: calendar_id
    - secretKey: GOOGLE_CALENDAR_API_KEY
      remoteRef:
        key: google_calendar
        property: api_key