apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - limitrange.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - secrets.yaml
  - service.yaml
  - ingress.yaml
  - datasources.yaml
  - dashboards-provider.yaml
  - statefulset.yaml
  - dashboards/
