apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin_password
      remoteRef:
        key: grafana
        property: admin_password
    - secretKey: discord_webhook_url
      remoteRef:
        key: grafana
        property: discord_webhook_url
