apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-directus-credentials
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-directus-credentials
    creationPolicy: Owner
  data:
    - secretKey: DIRECTUS_ACCESS_KEY
      remoteRef:
        key: minio
        property: access_key
    - secretKey: DIRECTUS_SECRET_KEY
      remoteRef:
        key: minio
        property: secret_key
