apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secrets
  namespace: vm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-secrets
    creationPolicy: Owner
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: alertmanager
        property: discord_webhook
    - secretKey: users
      remoteRef:
        key: alertmanager
        property: basic_auth_users
